```{r}
install.packages("dplyr")
install.packages("readr")
install.packages("ggplot2")
library(dplyr)
library(readr)
library(ggplot2)
```

```{r}
Perfumes_Masculinos = read.csv("ebay_mens_perfume.csv", na.strings = "", stringsAsFactors = T)
Perfumes_Masculinos
colnames(Perfumes_Masculinos) = c("Marca", "Titulo", "Tipo", "Preço", "Preço_em_U$", "Disponiveis", "Descrição_de_Disponibilidade", "Vendidos", "Ultima_Atualização", "Localização_Item" )

Perfumes_Masculinos$Disponiveis[grepl("Last One", Perfumes_Masculinos$Descrição_de_Disponibilidade , ignore.case = TRUE)] = 1
Perfumes_Masculinos$Disponiveis[grepl("Limited quantity available", Perfumes_Masculinos$Descrição_de_Disponibilidade , ignore.case = TRUE)] = 0

Perfumes_Masculinos[!complete.cases(Perfumes_Masculinos$Disponiveis),]$Disponiveis = 0
Perfumes_Masculinos[!complete.cases(Perfumes_Masculinos$Vendidos),]$Vendidos = 0
Perfumes_Masculinos[!complete.cases(Perfumes_Masculinos),]

Perfumes_Masculinos = Perfumes_Masculinos %>% select(-Ultima_Atualização)
Perfumes_Masculinos[717, "Disponiveis"] = 30
Perfumes_Masculinos[935, "Disponiveis"] = 100
Perfumes_Masculinos = Perfumes_Masculinos %>% slice(-c(82,139,151,404,566,685,791,796,898))

Perfumes_Masculinos[Perfumes_Masculinos$Tipo == "N/A",]$Tipo = "Eau de Parfum"
Perfumes_Masculinos[Perfumes_Masculinos$Marca == "Milestone Perfumes",]
Perfumes_Masculinos[Perfumes_Masculinos$Marca == "Unbranded",]
subset(Perfumes_Masculinos, grepl("Hawas for Men", Titulo , ignore.case = TRUE))
subset(Perfumes_Masculinos, grepl("California", Localização_Item , ignore.case = TRUE))
Perfumes_Masculinos$Localização_Item[grepl("Houston", Perfumes_Masculinos$Localização_Item , ignore.case = TRUE)] = "Houston, Texas, United States"

```

```{r}
Perfumes_Femininos = read.csv("ebay_womens_perfume.csv")
Perfumes_Femininos
colnames(Perfumes_Femininos) = c("Marca", "Titulo", "Tipo", "Preço", "Preço_em_U$", "Disponiveis", "Descrição_de_Disponibilidade", "Vendidos", "Ultima_Atualização", "Localização_Item" )
sum(is.na(Perfumes_Femininos))
```

